version: '3'
 
services:
  agiledatabase:
    image: amapidatabase.azurecr.io/agiledatabase_dev:latest
    build: 
      context: ./AutoDumperAgile
      dockerfile: Dockerfile
    command: "--default-authentication-plugin=mysql_native_password --skip-mysqlx"
    ports:
      - "3306:3306"
    container_name: agiledatabase
    hostname: agiledatabase
    volumes:
      - mysql:/var/lib/mysql
    restart: always 

# Front
  agilemeterfront:
    image: amapifront.azurecr.io/agilemeterfront_dev:latest
    build: 
      context: ./front
      dockerfile: Dockerfile
      args:
        - 'BACKEND_HOST=agilemeter.4fad901eba544c68aeb3.westeurope.aksapp.io'
        - 'BACKEND_PORT=80'
#    networks:
#      - AgilemeterNetwork
    container_name: agilemeterfront
    hostname: agilemeterfront
    ports:
      - "4200:4200"
 
# API
  agilemeter:
    image: amapiback.azurecr.io/agilemeter_dev:latest
    build: 
      context: ./everisapi.API
      dockerfile: Dockerfile
#    networks:
#      - AgilemeterNetwork
    depends_on:
      - agiledatabase
    links:
      - agiledatabase:database
    container_name: agilemeter
    hostname: agilemeter
    ports:
      - "60406:60406"
      
volumes:
  mysql:
