version: '3.4'
 
services:

# MySql
  agiledatabase:
    image: agiledatabase
    build: 
      context: ./AutoDumperAgile
      dockerfile: Dockerfile
    command: "--default-authentication-plugin=mysql_native_password --skip-mysqlx"
    ports:
      - "3306:3306"
    container_name: agiledatabase
    hostname: agiledatabase
    volumes:
      - mysql:/var/lib/mysql
    restart: always 

# Front
  agilemeterfront:
    image: agilemeterfront
    build: 
      context: ./front
      dockerfile: Dockerfile
      args:
        - 'BACKEND_HOST=$BACKEND_HOST'
        - 'BACKEND_PORT=$BACKEND_PORT'
#    networks:
#      - AgilemeterNetwork
    container_name: agilemeterfront
    hostname: agilemeterfront
    ports:
      - "4200:4200"
 
# API
  agilemeter:
    image: agilemeter
    build: 
      context: ./everisapi.API
      dockerfile: Dockerfile
#    networks:
#      - AgilemeterNetwork
    depends_on:
      - agiledatabase
    links:
      - agiledatabase:database
    container_name: agilemeter
    hostname: agilemeter
    ports:
      - "60406:60406"

volumes:
  mysql:


#networks:
#  AgilemeterNetwork:
#    driver: bridge