apiVersion: v1
kind: Service
metadata:
  labels:
    service: jiravars
  name: jiravars
  namespace: monitoring
spec:
  ports:
  - name: "9300"
    port: 9300
    targetPort: 9300
  selector:
    service: jiravars
status:
  loadBalancer: {}
