{
 "title": "DevOps Dashboard",
 "tags": [ "Pods" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   { "name": "pod_name", "query": "${VAR_POD_NAME}" }
  ]
 },
 "panels": [
  {
   "title": "Pods CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_cpu_usage_seconds_total{pod_name=~\"[[pod_name]].*\", namespace=\"$namespace\", image!=\"\", pod_name!=\"\", container_name!=\"POD\", container_name!=\"\"}[1m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pods % CPU Used",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod_name=~\"[[pod_name]].*\", namespace=\"$namespace\", image!=\"\", pod_name!=\"\", container_name!=\"POD\", container_name!=\"\"}[1m])) *100"
    }
   ]
  },
  {
   "title": "Pods Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod_name=~\"[[pod_name]].*\", namespace=\"$namespace\", image!=\"\", pod_name!=\"\", container_name!=\"POD\", container_name!=\"\"})by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pods Total Memory Used",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod_name=~\"[[pod_name]].*\", namespace=\"$namespace\", image!=\"\", pod_name!=\"\", container_name!=\"POD\", container_name!=\"\"})/1000000"
    }
   ]
  },
  {
   "title": "Pods Disk Space used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{pod_name=~\"[[pod_name]].*\", namespace=\"$namespace\", image!=\"\", pod_name!=\"\", container_name!=\"POD\", container_name!=\"\"}) by (pod_name)/10000",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pods Total Disk Space Used",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 16 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{pod_name=~\"[[pod_name]].*\", namespace=\"$namespace\", image!=\"\", pod_name!=\"\", container_name!=\"POD\", container_name!=\"\"})/10000"
    }
   ]
  },
  {
   "title": "Network RX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_network_receive_bytes_total{pod_name=~\"[[pod_name]].*\", namespace=~\"[[namespace]].*\"}[5m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Network TX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_network_transmit_bytes_total{pod_name=~\"[[pod_name]].*\", namespace=~\"[[namespace]].*\"}[5m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Network I/O pressure for Namespace $namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{pod_name=~\"[[pod_name]].*\", namespace=~\"[[namespace]].*\"}[5m])) by (namespace)\r\n",
     "legendFormat": "-> {{namespace}} Namespace"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{pod_name=~\"[[pod_name]].*\", namespace=~\"[[namespace]].*\"}[5m])) by (namespace)\r\n",
     "legendFormat": "<- {{namespace}} Namespace"
    }
   ]
  },
  {
   "title": "Pods network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{pod_name=~\"[[pod_name]].*\", namespace=~\"[[namespace]].*\"}[1m])) by (pod_name)",
     "legendFormat": "-> {{ pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{pod_name=~\"[[pod_name]].*\", namespace=~\"[[namespace]].*\"}[1m])) by (pod_name)",
     "legendFormat": "<- {{ pod_name }}"
    }
   ]
  },
  {
   "title": "CPU per namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name!=\"POD\",namespace!=\"\"}[5m])) by (namespace)\r\n",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}