{
 "title": "GitLab",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Project Size",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "gitlab_project_repository_size{repo=\"INNOVASEV___ScrumMeter\"}/1024000",
     "legendFormat": "Project Size"
    }
   ]
  },
  {
   "title": "LFS objects in Repo",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "gitlab_project_lfs_object_size{repo=\"INNOVASEV___ScrumMeter\"}",
     "legendFormat": "LFS"
    }
   ]
  },
  {
   "title": "GitLab Last Update",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "gitlab_project_last_activity{repo=\"INNOVASEV___ScrumMeter\"}*1000",
     "legendFormat": "Lat updated time"
    }
   ]
  },
  {
   "title": "GitLab",
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 19, "y": 0 },
   "content": "<img src=\"https://about.gitlab.com/images/devops-tools/gitlab-logo.svg\"  height=\"210\" align=\"middle\">"
  },
  {
   "title": "Commits on last 7 days",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "locale", "label": "Commits" }
   ],
   "targets": [
    {
     "expr": "irate(gitlab_project_commit_count{repo=\"INNOVASEV___ScrumMeter\"}[1d])",
     "legendFormat": "Commits"
    }
   ]
  },
  {
   "title": "Repo Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "irate(gitlab_project_last_activity{repo=\"INNOVASEV___ScrumMeter\"}[1d])",
     "legendFormat": "Activity"
    }
   ]
  }
 ]
}