version: '3'

services:
  agilemeter_jenkins:
    container_name: agilemeter_jenkins 
    build: ./jenkins
    hostname: jenkins
    environment:  
      #JAVA_OPTS: "-Djava.awt.headless=true"  
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false" # Start jenkins unlocked 
    ports:
      - 8081:8080
      - 50001:50001
    expose:
      - 8080
      - 50000
    volumes:
      - ./jenkins/volumes/users:/var/jenkins_home/users
      - ./jenkins/volumes/jobs:/var/jenkins_home/jobs
    networks: 
      - sonarnet
  sonarqube:
    hostname: sonaragile
    depends_on: 
      - db
    image: sonarqube:lts
    expose:
      - 9000
    ports:
      - 9000:9000
    networks: 
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    #volumes:
    # - ./sonarqube/conf:/opt/sonarqube/conf
    # - ./sonarqube/data:/opt/sonarqube/data
    # - ./sonarqube/extensions/plugins:/opt/sonarqube/extensions/plugins
    # - ./sonarqube/bundled-plugins:/opt/sonarqube/lib/bundled-plugins
  db:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
   # volumes:
   #   - ./sonarqube/postgresql/postgresql:/var/lib/postgresql
   #   - ./sonarqube/postgresql/data:/var/lib/postgresql/data
networks:
  sonarnet:
  