version: '3'

services:
  db:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./sonarqube/postgresql/postgresql:/var/lib/postgresql
      - ./sonarqube/postgresql/data:/var/lib/postgresql/data
  sonarqube:
    depends_on: 
      - db
    image: sonarqube:lts
      #build: ./sonarqube
    expose:
      - 9000
    ports:
      - 9000:9000
    networks: 
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    #volumes:
      - ./sonarqube/conf:/opt/sonarqube/conf
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/extensions/plugins:/opt/sonarqube/extensions/plugins
      - ./sonarqube/bundled-plugins:/opt/sonarqube/lib/bundled-plugins
networks:
  sonarnet: