<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tspan_ValoracionGlobal</name>
   <tag></tag>
   <elementGuidId>cf636957-0af0-41d2-8577-afdb7f4cbe0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;total&quot;]/circle-progress/descendant::*[name()='tspan'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;total&quot;]/circle-progress/descendant::*[name()='tspan'][1]</value>
   </webElementProperties>
</WebElementEntity>
