<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ColResultados</name>
   <tag></tag>
   <elementGuidId>875c1d7c-3174-4bf4-aa7e-8f948ad5f410</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tbody/tr[1]/td[count(//table/descendant::th/descendant::button[text()='${columna}']/preceding::th)+1]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody/tr[1]/td[count(//table/descendant::th/descendant::button[text()='${columna}']/preceding::th)+1]/button</value>
   </webElementProperties>
</WebElementEntity>
