<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tbody_ValorColumna</name>
   <tag></tag>
   <elementGuidId>068c8f38-1008-400c-921d-01463f0f383c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tbody/tr[1]/td[count(//table/descendant::th/descendant::button[text()='${columna}']/preceding::th)+1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody/tr[1]/td[count(//table/descendant::th/descendant::button[text()='${columna}']/preceding::th)+1]</value>
   </webElementProperties>
</WebElementEntity>
