apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.application.name }}-mysql-config
  labels:
    app: {{ .Values.application.name | quote }}
    role: mysql
data:
  agilemeter.cnf: |-
    [mysqld]
    lower_case_table_names = 1