apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}-{{ .Values.deployment.project_name }}-mysql
  labels:
    app: {{ .Values.application.name | quote }}
    deleteme: {{ .Values.application.deleteme | quote }}
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: {{ .Values.application.name }}-{{ .Values.deployment.project_name }}-mysql