kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.application.name }}-mysql
  labels:
    app: {{ .Values.application.name }}
    deleteme: {{ .Values.application.deleteme | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.capacity | quote }}