apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}-{{ .Values.deployment.project_name }}-frontend
  labels:
    app: {{ .Values.application.name | quote }}
    deleteme: {{ .Values.application.deleteme | quote }}
spec:
  type: ClusterIP
  ports:
    - name: frontend
      port: 4200
      targetPort: 4200
      protocol: TCP
  selector:
    app: {{ .Values.application.name }}-{{ .Values.deployment.project_name }}-frontend